# Generated by Django 5.1.5 on 2025-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaenvio',
            name='nome',
            field=models.CharField(choices=[('transportadora_local', 'Transportadora Local'), ('moto', 'Moto'), ('retirada_loja', 'Retirada na Loja'), ('entrega_rapida', 'Entrega Rápida (Mesmo Dia)'), ('entrega_economica', 'Entrega Económica'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Nome'),
        ),
    ]
