# Generated by Django 5.1.5 on 2025-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_formaenvio_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Pagamento'),
        ),
    ]
