# Generated by Django 5.1.5 on 2025-03-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa')),
                ('prazo_processamento', models.IntegerField(default=0, verbose_name='Prazo de Processamento (dias)')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código da Transação')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Processamento')),
                ('detalhes_pagamento', models.TextField(blank=True, null=True, verbose_name='Detalhes do Pagamento')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.metodopagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_processamento'],
            },
        ),
    ]
