# Generated by Django 5.1.5 on 2025-04-02 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_metodopagamento_options_metodopagamento_banco_and_more'),
        ('pedidos', '0002_alter_formaenvio_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_processamento', '-data_criacao'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/%Y/%m/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Confirmação'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='fonte_confirmacao',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('automatica', 'Automática'), ('bancaria', 'Confirmação Bancária'), ('cliente', 'Cliente'), ('api', 'API/Gateway')], max_length=20, null=True, verbose_name='Fonte de Confirmação'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='observacoes_internas',
            field=models.TextField(blank=True, help_text='Observações internas visíveis apenas para os administradores', null=True, verbose_name='Observações Internas'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='referencia_pagamento',
            field=models.CharField(blank=True, help_text='Referência utilizada pelo cliente para realizar o pagamento', max_length=100, null=True, verbose_name='Referência do Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Valor original sem taxas', max_digits=10, verbose_name='Valor Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_taxa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor da taxa aplicada', max_digits=10, verbose_name='Valor da Taxa'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.metodopagamento', verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=30, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor total com taxas incluídas', max_digits=10, verbose_name='Valor Total'),
        ),
    ]
