# Generated by Django 5.1.5 on 2025-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionario'), ('vendedor', 'Vendedor'), ('admin', 'Administrador')], default='cliente', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
