# Generated by Django 5.1.5 on 2025-03-30 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_visita_avaliacao_variacaoproduto'),
        ('usuarios', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDesejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Desejo',
                'verbose_name_plural': 'Listas de Desejo',
                'ordering': ['-data_adicao'],
                'unique_together': {('usuario', 'produto')},
            },
        ),
    ]
